sudo: required
services:
  - docker
language:
  - erlang
otp_release:
  - 18.0
install:
  - git --git-dir=/dev/null clone --depth=1 file://$PWD test/repo
  - docker build -t elmer_compiler/test test/
script:
  - docker run elmer_compiler/test
