sudo: required
services:
  - docker
language:
  - erlang
otp_release:
  - 18.0
install:
  - docker build -t elm_compiler/test test/
script:
  - docker run elm_compiler/test /bin/sh -c 'cd elm_compiler && rebar3 eunit'
